spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?$useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: test123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      auto-commit: true
      pool-name: mysql-pool